-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Users"
(
    id integer NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    "verifyEmail" boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."StaffUsers"
(
    staff_id integer NOT NULL,
    "staff_firstName" character varying(100) NOT NULL,
    "staff_lastName" character varying(100) NOT NULL,
    "staff_roleId" integer NOT NULL,
    PRIMARY KEY (staff_id)
);

CREATE TABLE public."JobSeekers"
(
    job_seeker_id integer NOT NULL,
    "job_seeker_firstName" character varying(100) NOT NULL,
    "job_seeker_lastName" character varying(100) NOT NULL,
    "job_seeker_nationaldentityNumber" character varying(11) NOT NULL,
    "job_seeker_birthDate" date NOT NULL,
    job_seeker_mernis boolean NOT NULL,
    PRIMARY KEY (job_seeker_id)
);

CREATE TABLE public."Employers"
(
    employers_id integer NOT NULL,
    "employers_webSite" character varying(100) NOT NULL,
    "employers_companyName" character varying(100) NOT NULL,
    "employers_phoneNumber" character varying(20) NOT NULL,
    "employers_verifiedBySystem" boolean NOT NULL,
    employers_password character varying(100) NOT NULL,
    PRIMARY KEY (employers_id)
);

CREATE TABLE public."Positions"
(
    position_id integer NOT NULL,
    position_name character varying(100) NOT NULL,
    PRIMARY KEY (position_id)
);

CREATE TABLE public."Roles"
(
    roles_id integer NOT NULL,
    roles_name character varying(100) NOT NULL,
    PRIMARY KEY (roles_id)
);

ALTER TABLE public."StaffUsers"
    ADD FOREIGN KEY (staff_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."JobSeekers"
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Employers"
    ADD FOREIGN KEY (employers_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."StaffUsers"
    ADD FOREIGN KEY ("staff_roleId")
    REFERENCES public."Roles" (roles_id)
    NOT VALID;

END;